// This file will be auto-generated by Supabase CLI
// For now, we define a placeholder type

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // Roles configuration (global, not per-game)
      roles: {
        Row: {
          id: string;
          name: string;
          display_name: string;
          team: 'village' | 'loups' | 'solo';
          description: string;
          icon: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          display_name: string;
          team: 'village' | 'loups' | 'solo';
          description: string;
          icon?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          display_name?: string;
          team?: 'village' | 'loups' | 'solo';
          description?: string;
          icon?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      // Powers linked to roles
      powers: {
        Row: {
          id: string;
          role_id: string;
          name: string;
          description: string;
          phase: 'nuit' | 'jour' | 'mort';
          uses_per_game: number | null;
          priority: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          role_id: string;
          name: string;
          description: string;
          phase: 'nuit' | 'jour' | 'mort';
          uses_per_game?: number | null;
          priority: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          role_id?: string;
          name?: string;
          description?: string;
          phase?: 'nuit' | 'jour' | 'mort';
          uses_per_game?: number | null;
          priority?: number;
          created_at?: string;
        };
      };
      // Games/Parties
      games: {
        Row: {
          id: string;
          code: string;
          name: string;
          status: 'lobby' | 'jour' | 'nuit' | 'conseil' | 'terminee';
          current_phase: number;
          settings: Json;
          created_at: string;
          started_at: string | null;
          ended_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          status?: 'lobby' | 'jour' | 'nuit' | 'conseil' | 'terminee';
          current_phase?: number;
          settings?: Json;
          created_at?: string;
          started_at?: string | null;
          ended_at?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          status?: 'lobby' | 'jour' | 'nuit' | 'conseil' | 'terminee';
          current_phase?: number;
          settings?: Json;
          created_at?: string;
          started_at?: string | null;
          ended_at?: string | null;
        };
      };
      // Players in a game
      players: {
        Row: {
          id: string;
          game_id: string;
          user_id: string | null;
          pseudo: string;
          role_id: string | null;
          is_alive: boolean;
          is_mj: boolean;
          death_reason: string | null;
          death_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          user_id?: string | null;
          pseudo: string;
          role_id?: string | null;
          is_alive?: boolean;
          is_mj?: boolean;
          death_reason?: string | null;
          death_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          user_id?: string | null;
          pseudo?: string;
          role_id?: string | null;
          is_alive?: boolean;
          is_mj?: boolean;
          death_reason?: string | null;
          death_at?: string | null;
          created_at?: string;
        };
      };
      // Missions
      missions: {
        Row: {
          id: string;
          game_id: string;
          title: string;
          description: string;
          type: string;
          status: 'pending' | 'in_progress' | 'success' | 'failed' | 'cancelled';
          assigned_to: string | null;
          deadline: string | null;
          validated_by: string | null;
          validated_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          title: string;
          description: string;
          type: string;
          status?: 'pending' | 'in_progress' | 'success' | 'failed' | 'cancelled';
          assigned_to?: string | null;
          deadline?: string | null;
          validated_by?: string | null;
          validated_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          title?: string;
          description?: string;
          type?: string;
          status?: 'pending' | 'in_progress' | 'success' | 'failed' | 'cancelled';
          assigned_to?: string | null;
          deadline?: string | null;
          validated_by?: string | null;
          validated_at?: string | null;
          created_at?: string;
        };
      };
      // Votes (day and night)
      votes: {
        Row: {
          id: string;
          game_id: string;
          phase: number;
          voter_id: string;
          target_id: string | null;
          vote_type: 'jour' | 'nuit_loup' | 'pouvoir';
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          phase: number;
          voter_id: string;
          target_id?: string | null;
          vote_type: 'jour' | 'nuit_loup' | 'pouvoir';
          created_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          phase?: number;
          voter_id?: string;
          target_id?: string | null;
          vote_type?: 'jour' | 'nuit_loup' | 'pouvoir';
          created_at?: string;
        };
      };
      // Wolf chat
      wolf_chat: {
        Row: {
          id: string;
          game_id: string;
          player_id: string;
          message: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          player_id: string;
          message: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          player_id?: string;
          message?: string;
          created_at?: string;
        };
      };
      // Game events log (audit trail)
      game_events: {
        Row: {
          id: string;
          game_id: string;
          event_type: string;
          actor_id: string | null;
          target_id: string | null;
          data: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          event_type: string;
          actor_id?: string | null;
          target_id?: string | null;
          data?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          event_type?: string;
          actor_id?: string | null;
          target_id?: string | null;
          data?: Json;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
